import fs from "node:fs";

const esmSource = fs.readFileSync("./json-with-bigint.js", "utf-8");

const prefix = `"use strict";

// This file is auto-generated. Do not edit this file directly.

`;

const cjsSource =
  prefix + esmSource.replace(/export\s+{([^}]+)};/g, "module.exports = {$1};");

fs.writeFileSync("./json-with-bigint.cjs", cjsSource, "utf-8");
